---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Installer Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: S'aasurer que Docker demarre au boot du
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Activer les notification
  meta: flush_handlers

- include_tasks: compose.yml
  when: docker_install_compose | bool

- include_tasks: deploy.yml

- include_tasks: build.yml

- include_tasks: docker-users.yml
  when: docker_users | length > 0
